version: '2.4'

services:
  Ender_5_Pro:
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
      - 5000:5000
      - 8080:8080
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/video0:/dev/video1
    volumes:
      - /root/octoprint/ender_5_pro:/octoprint
    environment:
      - ENABLE_MJPG_STREAMER=true
      - CAMERA_DEV=/dev/video1
      - MJPG_STREAMER_INPUT=-n -r 1280x960 -f 30
  Artillery_X1:
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
      - 5555:5000
      - 8081:8080
    devices:
      - /dev/ttyUSB0:/dev/ttyACM0
      - /dev/video2:/dev/video0
    volumes:
      - /root/octoprint/artillery_x1:/octoprint
    environment:
      - ENABLE_MJPG_STREAMER=true
      - CAMERA_DEV=/dev/video0
      - MJPG_STREAMER_INPUT=-n -r 1280x960 -f 30