global:
  scrape_interval:     30s # El intervalo en el que se traerá las métricas
  evaluation_interval: 30s # Evaluará las reglas cada 30 segundos, por defecto es cada minuto

scrape_configs:

  - job_name: 'node_exporter'
    static_configs:
    - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']

  - job_name: 'ender5pro'
    metrics_path: '/plugin/prometheus_exporter/metrics'
    params:
      apikey: ['---API_OCTOPRINT---']
    static_configs:
    - targets: ['192.168.0.222:8001']

  - job_name: 'artilleryx1'
    metrics_path: '/plugin/prometheus_exporter/metrics'
    params:
      apikey: ['---API_OCTOPRINT---']
    static_configs:
    - targets: ['192.168.0.222:8002']